ALTER TABLE subscriptions_list RENAME COLUMN status to billing_status;

ALTER TABLE templates ADD COLUMN welcome_image_url TEXT;

UPDATE templates SET welcome_image_url = 'https://res.cloudinary.com/djcitu2qx/image/upload/v1686220689/WelcomeFood_e1yvnn.png' WHERE id = 2;

UPDATE templates SET welcome_image_url = 'https://res.cloudinary.com/djcitu2qx/image/upload/v1686220690/WelcomeFood2_mdxrpn.png' WHERE id = 3;

UPDATE templates SET welcome_image_url = 'https://res.cloudinary.com/djcitu2qx/image/upload/v1686220689/WelcomeNature_zl0rzu.png' WHERE id = 4;

UPDATE templates SET welcome_image_url = 'https://res.cloudinary.com/djcitu2qx/image/upload/v1686220689/WelcomeClothing_d1kzuy.png' WHERE id = 5;

UPDATE templates SET welcome_image_url = 'https://res.cloudinary.com/djcitu2qx/image/upload/v1686220689/WelcomeJewelry_ebkegg.png' WHERE id = 6;

CREATE TABLE public.campaign_details
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    campaign_id integer NOT NULL,
    is_draft boolean NOT NULL,
    is_active boolean NOT NULL,
    landing_template_link text COLLATE pg_catalog."default",
    rewards_template_link text COLLATE pg_catalog."default",
    landing_page_link text COLLATE pg_catalog."default",
    rewards_page_link text COLLATE pg_catalog."default",
    discount_code_1 text COLLATE pg_catalog."default",
    discount_code_2 text COLLATE pg_catalog."default",
    discount_code_3 text COLLATE pg_catalog."default",
    discount_code_4 text COLLATE pg_catalog."default",
    CONSTRAINT campaign_details_pkey PRIMARY KEY (id),
    CONSTRAINT "campaignID" FOREIGN KEY (id)
        REFERENCES public.campaign_settings (campaign_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)
