CREATE TABLE IF NOT EXISTS public.order_details 
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    order_id bigint NOT NULL,
    order_name text COLLATE pg_catalog."default",
    created_at text COLLATE pg_catalog."default",
    subtotal_price FLOAT,
    total_discounts FLOAT,
    total_tax FLOAT,
    total_price FLOAT,
    discount_codes text COLLATE pg_catalog."default",
    currency text COLLATE pg_catalog."default",
    customer_email text COLLATE pg_catalog."default",
    customer_tags text COLLATE pg_catalog."default",
    shop_id text COLLATE pg_catalog."default" NOT NULL
);

ALTER TABLE ONLY public.order_details
    ADD CONSTRAINT order_details_pkey PRIMARY KEY (id);