DROP TABLE IF EXISTS public.campaign_details;

CREATE TABLE IF NOT EXISTS public.campaign_details (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    campaign_id integer NOT NULL,
    is_draft boolean NOT NULL,
    is_active boolean NOT NULL,
    theme_id text COLLATE pg_catalog."default",
    landing_template_key text COLLATE pg_catalog."default",
    rewards_template_key text COLLATE pg_catalog."default",
    landing_page_id text COLLATE pg_catalog."default",
    rewards_page_id text COLLATE pg_catalog."default",
    landing_template_link text COLLATE pg_catalog."default",
    rewards_template_link text COLLATE pg_catalog."default",
    landing_page_link text COLLATE pg_catalog."default",
    rewards_page_link text COLLATE pg_catalog."default",
    tier1_segment_id text COLLATE pg_catalog."default",
    tier2_segment_id text COLLATE pg_catalog."default",
    tier3_segment_id text COLLATE pg_catalog."default",
    tier4_segment_id text COLLATE pg_catalog."default",
    tier1_price_rule_id text COLLATE pg_catalog."default",
    tier2_price_rule_id text COLLATE pg_catalog."default",
    tier3_price_rule_id text COLLATE pg_catalog."default",
    tier4_price_rule_id text COLLATE pg_catalog."default",
    discount_code_1 text COLLATE pg_catalog."default",
    discount_code_2 text COLLATE pg_catalog."default",
    discount_code_3 text COLLATE pg_catalog."default",
    discount_code_4 text COLLATE pg_catalog."default",
    shop_id text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT campaign_details_pkey PRIMARY KEY (id),
    CONSTRAINT "campaignID" FOREIGN KEY (campaign_id)
    REFERENCES public.campaign_settings (campaign_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
);