# This file stores configurations for your Shopify app.

scopes = "read_orders, read_products, read_content, write_content, read_themes, write_themes, read_price_rules, write_price_rules, read_customers, write_customers"
