# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Viral Launch"
client_id = "727cd09b9cbefbb4a3dd7edc977070cd"
application_url = "https://xychrosapp.herokuapp.com/"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_content,write_content,read_themes,write_themes,read_price_rules,write_price_rules,read_customers,write_customers"

[auth]
redirect_urls = [
  "https://xychrosapp.herokuapp.com/auth/callback",
  "https://xychrosapp.herokuapp.com/auth/shopify/callback",
  "https://xychrosapp.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"
[app_proxy]
url = "https://xychrosapp.herokuapp.com/"
subpath = "product-prelauncher"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "xychros-product-prelauncher.myshopify.com"
