# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "XychrosUpdatedTestServer"
client_id = "038304675f7b4a7b2b16705368a68a45"
application_url = "https://xychrostest-6ab89d0ac1e3.herokuapp.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders, read_products, read_content, write_content, read_themes, write_themes, read_price_rules, write_price_rules, read_customers, write_customers"

[auth]
redirect_urls = [
  "https://xychrostest-6ab89d0ac1e3.herokuapp.com/auth/callback",
  "https://xychrostest-6ab89d0ac1e3.herokuapp.com/auth/shopify/callback",
  "https://xychrostest-6ab89d0ac1e3.herokuapp.com/api/auth/callback"
]

[webhooks]
api_version = "2023-07"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "xychrostest.myshopify.com"
