# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "test-2-app"
client_id = "5c477447c78bc3bbdecf326daf0aaab6"
application_url = "https://learned-such-pgp-vi.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_content,write_content,read_themes,write_themes,read_price_rules,write_price_rules,read_customers,write_customers,read_discounts"

[auth]
redirect_urls = [
  "https://learned-such-pgp-vi.trycloudflare.com/auth/callback",
  "https://learned-such-pgp-vi.trycloudflare.com/auth/shopify/callback",
  "https://learned-such-pgp-vi.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2022-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://teen-wings-fees-hill.trycloudflare.com/api/webhooks"
  customer_data_request_url = "https://teen-wings-fees-hill.trycloudflare.com/api/webhooks"
  shop_deletion_url = "https://teen-wings-fees-hill.trycloudflare.com/api/webhooks"

[app_proxy]
url = "https://learned-such-pgp-vi.trycloudflare.com"
subpath = "test-2-app"
prefix = "apps"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "app-running.myshopify.com"
